namespace Utils.Exceptions
{
    internal class AlreadyExistsException : Exception
    {
        
    }
}
